mqtt:
  broker: localhost
  port: 1883
  username: null
  password: null
  topic_prefix: meshcore
  qos: 0
  retain: false

meshcore:
  connection_type: tcp
  address: "192.168.1.100"
  port: 12345
  baudrate: 115200
  timeout: 5
  events:
    - CONTACT_MSG_RECV
    - CHANNEL_MSG_RECV
    - CONNECTED
    - DISCONNECTED
    - LOGIN_SUCCESS
    - LOGIN_FAILED
    - MESSAGES_WAITING
    - DEVICE_INFO
    - BATTERY
    - NEW_CONTACT

log_level: INFO